### ISSUE TITLE
FuzzyOpen changes the working directory of vim to the the parent dir of the file

### ISSUE THREAD

**Issue by bbatha** [cloudhead/neovim-fuzzy#10]
Opening a file is now changing the cwd of vim or fzy such that subsequent uses of FuzzyOpen only search the folder the last file was found in.

**Comment by cloudhead** [comment]
I can't reproduce this. Are you inside a .git repo or not?

**Comment by bbatha** [comment]
I am in a git repo

**Comment by tssm** [comment]
I have encounter a weird issue that can be related: some times all the filesystem files disappear from the fuzzy list and only the open buffers remain. I have tried to isolate when it happens without luck.

**Comment by cloudhead** [comment]
I've had this issue, and on my side it had to do with my `/tmp` dir being full. The plugin creates a temporary file there to interface with the cli.

**Comment by tssm** [comment]
@cloudhead how is called that temporary file? I would like to help debugging this. I think @bbatha problem is the same.

**Comment by bbatha** [comment]
I checked my machine, my /tmp dir has several GB free. I also set my vim's tmp dir through `backupdir` and `directory` to be a directory in my home folder, which also has a lot of space in it.

**Comment by cloudhead** [comment]
@tssm what makes you think it's the same problem? The temp file name is always different, but you can get an idea by running:

`:echom tempname()`

in nvim.

**Comment by tssm** [comment]
Just a hunch. I don't know if @bbatha has checked `:pwd` and/or `getcwd()` but in my case sometimes it seems like the working directory changed (`:FuzzyOpen` only shows files from `src/` because I only opened files from that dir) but in fact it didn't (`pwd` returns the expected working dir).

**Comment by bbatha** [comment]
I'm actually seeing the same behavior as @tssm my `:pwd` is still the same but `:FuzzyOpen` acts like my pwd is in a child-folder, usually the one containing the file I last opened through `:FuzzyOpen`. It does not happen every time I open a file with `:FuzzyOpen` though.

**Comment by cloudhead** [comment]
Can you both check if the problem exists with the `noroot` branch? With vimplug you can do:

```
Plug 'cloudhead/neovim-fuzzy', { 'branch': 'noroot' }
```

This branch is reset to an older commit which doesn't base your search path on whether or not you're in a git repo. I suspect that could be what is causing the problem.

**Comment by cloudhead** [comment]
Also I forgot to ask, what is shown in the fuzzy open status bar? The correct search dir or the incorrect one? ie:

```
FuzzyOpen ~/src/neovim-fuzzy (2 files)
```

**Comment by cloudhead** [comment]
And finally, is anyone of you using `set autochdir` in your vim configs?

**Comment by tssm** [comment]
@cloudhead just installed the plug-in from the `noroot` branch, let's see what happens.

`FuzzyOpen` always show the correct search dir and I don't have `autochdir` on `$MYVIMRC`.

**Comment by tssm** [comment]
@cloudhead same issue on `noroot` branch, but this time I realized that the status line is wrong: it says `FuzzyOpen (23 files)` so no current dir (although `:pwd` reports the expected dir).

**Comment by tssm** [comment]
@cloudhead just realized that the smaller status line is part of the `noroot` branch.

**Comment by cloudhead** [comment]
In the current master branch, the status bar shows the search root, since the search root is not necessarily your pwd, it could be for instance the git root if you're in a repo.

In the noroot branch, this feature does not exist, and hence the search root is always the pwd, so nothing is shown on the status line.

So from what I understand, the issue you're having is not related to that feature, since you're having it with the noroot branch too. That narrows things down!

**Comment by tssm** [comment]
Yep, it occurs on `noroot` too. It's pretty weird: the plug-in always starts working. I think some usage pattern makes it behave badly. Any other thing that you like s to try?

**Comment by tssm** [comment]
@cloudhead I think I found the problem (in both `master` and `noroot`): when I do a search using `:grep` (directly or through a plug-in) the issue appears. Normally I use [Grepper](https://github.com/mhinz/vim-grepper) for search and if I close the quick fix list Fuzzy behaves normal again. If I use `:grep` directly I need to restart Neovim. @bbatha can you confirm that this is the problem?

**Comment by bbatha** [comment]
I can't seem to reproduce on either branch any more. I'm wondering if one of my other plugins caused the issue.

**Comment by cloudhead** [comment]
@tssm great, will see if I can reproduce!

**Comment by cloudhead** [comment]
I haven't been able to reproduce, but I've recently run into another issue, and I'm wondering if there's a chance they are related: it happens when netrw is used, for example by using `:E`. Looking into this at the moment.

**Comment by tssm** [comment]
@cloudhead yeah, I have seen a similar behavior using [FileBeagle](https://github.com/jeetsukumaran/vim-filebeagle) (a netrw replacement) but seems to be random...

**Comment by silenc3r** [comment]
I can reproduce this behavior with [vim-signify](https://github.com/mhinz/vim-signify) enabled.

**Comment by tssm** [comment]
I think since one of the last commits I haven't experienced this behavior again. At least not that often. Can someone else confirm?

**Comment by cloudhead** [comment]
In a recent patch I fixed an issue when the quickfix list is open, so it might have been the same bug.

**Comment by tssm** [comment]
Yeah, that's what I thought when I saw the git log. Anyone else can confirm?

**Comment by tssm** [comment]
Playing around trying to fix #24 I realized that the behavior described by me on this issue is related to the quick fix window, which was fixed long ago, so I would close this unless @bbatha and @silenc3r still experience weird behavior

**Comment by cloudhead** [comment]
I'll close this for now.

**Comment by smarquez1** [comment]
This recently started happening to me. I red the comments on this issue and found out that it stops happenning when I disable the `vim-signify` plugin. I checked out the latest changes on said plugin and found a commit that might be related: https://github.com/mhinz/vim-signify/commit/ea6db3c7df7671584df0a37a2436a919332d0b7c

**Comment by IvRRimum** [comment]
This problem is present if you have `Plug 'fatih/vim-go'` present. If you disable it, then it doesnt change the current folder to target of your search, but the problem is that `vim-go`is super great problem, which i don't want to sacrifice :(

**Comment by cloudhead** [comment]
I'm guessing that the problem is caused by the use of the `lcd` command (local change dir). If we found a way to not use that command, the problem should go away.
